# Generated by Django 3.1.4 on 2020-12-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos', verbose_name='Foto'),
        ),
    ]
