# Generated by Django 3.1.4 on 2021-01-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_contacto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone'),
        ),
    ]
